spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto : validate
  liquibase:
     change-log: classpath:db/changelog/db.changelog-master.xml